### ISSUE TITLE
math domain error

### ISSUE THREAD

**Issue by Siteng999** [sklasfeld/DANPOS3#5]
Hello

When I am using DANPOS, some tasks have the following bug, is there any solution for it?

Gratefully, siteng

Traceback (most recent call last):
  File "/public/home/stbi/task/xxt/sequence/DANPOS3/danpos.py", line 1365, in <module>
    if sys.argv[1]=='dpos':runDANPOS(command='dpos')
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/stbi/task/xxt/sequence/DANPOS3/danpos.py", line 396, in runDANPOS
    danpos(\
  File "/public/home/stbi/task/xxt/sequence/DANPOS3/functions.py", line 506, in danpos
    allPositionsInOneFile(controlPositionFile=os.path.join(opath,'pooled',groupnames[1]+addname+"positions.ref_adjust.xls"),\
  File "/public/home/stbi/task/xxt/sequence/DANPOS3/functions.py", line 1172, in allPositionsInOneFile
    temp=log10fuztest(pc=p1,pt=p2,cr=cr,cwig=cwig,twig=twig,rd=rd)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/stbi/task/xxt/sequence/DANPOS3/functions.py", line 1342, in log10fuztest
    else:p=pf(unnumpy(div(vt,vc)),
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/public/home/stbi/task/xxt/sequence/DANPOS3/functions.py", line 66, in pf
    answer = log(answer)
             ^^^^^^^^^^^
ValueError: math domain error

**Comment by Siteng999** [comment]
Hi,@SimHolz

The functions.py can be normal workinng ! Thank you very much for your help

Gratefully, siteng

Here's a harmless bug：
/public/home/stbi/task/xxt/sequence/DANPOS3/functions.py:173: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if bggroupname is not 'None':
